sourceSets {
    main {
        java {
            srcDir 'src/main/java'
           
        }
        resources {
			srcDir 'src/main/resources'
			srcDir 'src/main/java'  exclude '**/*.java'
        }
        
    }
    test {
        java {
            srcDir 'src/test/java'
           
        }
        resources {
			srcDir 'src/test/resources'
			srcDir 'src/test/java'  exclude '**/*.java'
        }
        
    }
    
}


dependencies {
    api project(":bboss-ai")

//    compileOnly (
//            [group: "io.modelcontextprotocol.sdk", name: "mcp-core", version: "1.0.0"],
//    )
//    
//    {
//        exclude group: 'log4j', module: 'log4j'
//        exclude group: 'org.slf4j', module: 'slf4j-log4j12'
//        exclude group: 'org.slf4j', module: 'slf4j-api'
//        
//         
//    }
//    compileOnly (
//            [group: "io.modelcontextprotocol.sdk", name: "mcp-json-jackson2", version: "1.0.0"],
//    )
//
//    {
//        exclude group: 'log4j', module: 'log4j'
//        exclude group: 'org.slf4j', module: 'slf4j-log4j12'
//        exclude group: 'org.slf4j', module: 'slf4j-api'
//    }
    api group: 'com.bbossgroups.plugins', name: 'bboss-datatran-jdbc', version: bboss_es_version
    api group: 'com.bbossgroups', name: 'bboss-feishu', version: BBOSS_HTTP5_VERSION
    testCompileOnly  (
//				[group: 'mysql', name: 'mysql-connector-java', version: "${mysqlconnectorversion}", transitive: true]
            [group: 'com.mysql', name: 'mysql-connector-j', version: mysqlconnectorversion, transitive: false],


    )
//    api("org.jetbrains:markdown:0.7.3")
    api("com.vladsch.flexmark:flexmark-all:0.64.8")
    compileOnly  (
            [group: 'org.apache.groovy', name: 'groovy', version: groovy_version, transitive: true],

    ){
//            exclude group: 'org.apache.groovy', module: 'groovy-testng'
        exclude group: 'org.apache.groovy', module: 'groovy-test'
        exclude group: 'org.apache.groovy', module: 'groovy-test-junit5'

        exclude group: 'com.fasterxml.jackson.dataformat', module: 'jackson-dataformat-yaml'

        exclude group: 'com.fasterxml.jackson.core', module: 'jackson-databind'
        exclude group: 'com.github.javaparser', module: 'javaparser-core'

    }

    testImplementation  (
            [group: 'org.apache.groovy', name: 'groovy', version: groovy_version, transitive: true],

    ){
//            exclude group: 'org.apache.groovy', module: 'groovy-testng'
        exclude group: 'org.apache.groovy', module: 'groovy-test'
        exclude group: 'org.apache.groovy', module: 'groovy-test-junit5'

        exclude group: 'com.fasterxml.jackson.dataformat', module: 'jackson-dataformat-yaml'

        exclude group: 'com.fasterxml.jackson.core', module: 'jackson-databind'
        exclude group: 'com.github.javaparser', module: 'javaparser-core'

    }

    testImplementation(
            [group: 'com.clickhouse', name: 'clickhouse-jdbc', version: "0.9.8", transitive: true],
    )
            {
                exclude group: 'org.slf4j', module: 'slf4j-api'
                exclude group: 'commons-codec', module: 'commons-codec'
                exclude group: 'commons-io', module: 'commons-io'
                exclude group: 'org.ow2.asm', module: 'asm'
                exclude group: 'org.apache.commons', module: 'commons-lang3'
            }
}
